// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';
import localforage from 'localforage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Configure localforage for better PWA persistence
localforage.config({
  name: 'healthintegrityproject',
  storeName: 'auth',
  description: 'Authentication storage for HIP PWA'
});

// Create a wrapper to make localforage compatible with Supabase's storage interface
const supabaseStorage = {
  getItem: async (key: string): Promise<string | null> => {
    const value = await localforage.getItem<string>(key);
    logger.log('[Storage] getItem:', key, value ? '✅ Found' : '❌ Not found');
    return value;
  },
  setItem: async (key: string, value: string): Promise<void> => {
    await localforage.setItem(key, value);
    logger.log('[Storage] setItem:', key, '✅ Saved');
  },
  removeItem: async (key: string): Promise<void> => {
    await localforage.removeItem(key);
    logger.log('[Storage] removeItem:', key, '🗑️ Removed');
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: supabaseStorage, // IndexedDB-based storage for better PWA persistence
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Critical for OAuth flows (Google login)
    flowType: 'pkce', // More secure flow for SPAs/PWAs
  }
});
